name: Render R Markdown report

on:
  workflow_run:
    workflows: ["Scrape ECB Rates"]
    types:
      - completed
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libv8-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libglpk-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c(
            "rmarkdown", "ggplot2", "dplyr", "tidyr", "readr", "stringr", "tibble", "forcats",
            "lubridate", "forecast", "xgboost", "zoo", "lmtest", "igraph", "ggraph",
            "TTR", "curl", "httr", "quantmod", "tseries", "ggforce", "gganimate",
            "sf", "units", "transformr", "rsconnect", "covr", "gt",
            "juicyjuice", "katex", "V8", "systemfonts"
          ), dependencies = TRUE, repos = "https://cloud.r-project.org")'
          Rscript -e 'try(install.packages("prophet", repos = "https://cloud.r-project.org"))'

      - name: Check for data changes
        id: data-check
        run: |
          git fetch origin main
          if git diff --quiet origin/main -- data; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Render RMarkdown to HTML
        if: steps.data-check.outputs.changed == 'true'
        run: Rscript R/render_report.R

      - name: Commit rendered HTML
        if: steps.data-check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add report/index.html
          git diff --cached --quiet || git commit -m "ci: Render dashboard HTML from report.Rmd"
          git push
